export const mockItems = [
    {
        id: 1,
        name: 'Funko Gus Fring',
        price: 1000,
        priceUnit: 'CLP',
        imgSrc: '/img/funko.jpg',
        status: 'new',
    },
    {
        id: 2,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/pokemon-card.jpg',
        status: 'new',
    },
    {
        id: 3,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/ps1.webp',
        status: 'new',
    },
    {
        id: 4,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/funko.jpg',
        status: 'new',
    },
    {
        id: 5,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/pokemon-card.jpg',
        status: 'new',
    },
    {
        id: 6,
        name: 'Funko Gus Fring',
        price: 1000,
        priceUnit: 'CLP',
        imgSrc: '/img/ps1.webp',
        status: 'new',
    },
    {
        id: 7,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/funko.jpg',
        status: 'new',
    },
    {
        id: 8,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/pokemon-card.jpg',
        status: 'new',
    },
    {
        id: 9,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/ps1.webp',
        status: 'new',
    },
    {
        id: 10,
        name: 'Funko Gus Fring',
        price: 1500,
        priceUnit: 'CLP',
        imgSrc: '/img/funko.jpg',
        status: 'new',
    }
];